import Header from "./componentes/Header"
import Footer from "./componentes/Footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body style={{margin: 0}}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
